name: ChatReport
version: 1.0
main: me.centauri07.chatreport.plugin.ChatReportPlugin
api-version: 1.13
commands:
  chatreport:
    usage: /chatreport <player>
    description: report a message from a player

libraries:
  - net.dv8tion:JDA:5.0.0-beta.23
  - com.charleskorn.kaml:kaml:0.54.0